### GET all persons
GET http://localhost:8080/api/v1/persons
Authorization: Basic admin admin
Accept: application/json
###

### GET one person by id
GET http://localhost:8080/api/v1/persons/1
Authorization: Basic admin admin
Accept: application/json
###

### DELETE person
DELETE http://localhost:8080/api/v1/persons/2
Authorization: Basic admin admin
Accept: application/json
###

### POST person
POST http://localhost:8080/api/v1/persons
Authorization: Basic admin admin
Accept: application/json
Content-Type: application/json

{
  "name": "John",
  "age": "56"
}
###

### PUT person
PUT http://localhost:8080/api/v1/persons
Authorization: Basic admin admin
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "name": "Bobbb",
  "age": "24"
}
###

### GET Hello User
GET http://localhost:8080/api/v1/persons/user
Authorization: Basic admin admin
Accept: application/json
###

### GET Hello Admin
GET http://localhost:8080/api/v1/persons/admin
Authorization: Basic admin admin
Accept: application/json
###

### GET Hello Unknown
GET http://localhost:8080/api/v1/persons/unknown
Authorization: Basic admin admin
Accept: application/json
###